from __future__ import annotations

import inspect
import textwrap
from datetime import datetime, timezone

from .graph import Graph


class CompileError(Exception):
    pass


def _sanitize(name: str) -> str:
    out = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
    return out if out and not out[0].isdigit() else f"_{out}"


def compile_graph(
    graph: Graph,
    runner=None,
    output_blocks: list[str] | None = None,
    strict: bool = True,
) -> str:
    """Compile the graph to a single, self-contained Python script (plan
    section 7, default/clean mode — DataFramePacket/ColumnMeta scaffolding
    is absent by construction, since block bodies are plain-dataframe
    functions to begin with). `--with-metadata` verbose mode is not yet
    implemented.
    """
    targets = output_blocks or list(graph.blocks)
    reachable = graph.ancestors(targets)

    if runner is not None:
        not_ready = sorted(b for b in reachable if runner.status(b) in ("grey", "red"))
        if not_ready and strict:
            raise CompileError(f"blocks not ready to compile (grey/red): {not_ready}")

    order = [b for b in graph.topo_order() if b in reachable]

    fn_names: dict[str, str] = {}
    def_lines: list[str] = []
    for bid in order:
        block = graph.blocks[bid]
        fn = block.resolved_fn()
        src = block.code if block.block_type == "llm_authored" else inspect.getsource(fn)
        src = textwrap.dedent(src).strip("\n")
        fn_name = f"{_sanitize(block.category)}_{bid}"
        fn_names[bid] = fn_name
        src = src.replace(f"def {fn.__name__}(", f"def {fn_name}(", 1)
        phase = graph.lanes[block.lane].name if block.lane in graph.lanes else ""
        def_lines.append(
            f'# === Block: {bid} | type={block.block_type} | phase="{phase}" | name="{block.name}" ==='
        )
        def_lines.append(src)
        def_lines.append("")
        def_lines.append("")

    call_lines: list[str] = []
    var_names: dict[tuple[str, str], str] = {}
    for bid in order:
        block = graph.blocks[bid]
        kwargs = []
        for port, wire in sorted(graph.input_wires(bid).items()):
            kwargs.append(f"{port}={var_names[(wire.from_block, wire.from_port)]}")
        for pname, pval in block.params.items():
            kwargs.append(f"{pname}={pval!r}")
        if block.block_type == "output":
            kwargs.append("output_dir=OUTPUT_DIR")

        out_ports = [p.name for p in block.outputs]
        call = f"{fn_names[bid]}({', '.join(kwargs)})"
        call_lines.append(f"# --- Call: {bid} ---")
        if not out_ports:
            call_lines.append(call)
        elif len(out_ports) == 1:
            var = f"{_sanitize(block.name)}_{bid}"
            var_names[(bid, out_ports[0])] = var
            call_lines.append(f"{var} = {call}")
        else:
            varlist = []
            for p in out_ports:
                var = f"{_sanitize(block.name)}_{bid}_{p}"
                var_names[(bid, p)] = var
                varlist.append(var)
            call_lines.append(f"{', '.join(varlist)} = {call}")
        call_lines.append("")

    header = [
        "# Generated by Model-Maker. Do not edit function bodies here directly --",
        "# edit the source blocks in the project and recompile.",
        f"# Compiled: {datetime.now(timezone.utc).isoformat()}",
        "",
        "import os",
        "import polars as pl",
        "",
        'OUTPUT_DIR = os.environ.get("OUTPUT_DIR", "./output")',
        "os.makedirs(OUTPUT_DIR, exist_ok=True)",
        "",
        "",
    ]

    return "\n".join(header + def_lines + call_lines) + "\n"
